In [17]:
import pandas as pd
import numpy as np

#data split and model train test
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

#set path of current dict
%cd E:\M.Sc(DS & SA)\Sem-2\Data Driven Governance\Final Project Data\Datasets\Data for Tableau for NO2 CO2 PM\5 high Data

E:\M.Sc(DS & SA)\Sem-2\Data Driven Governance\Final Project Data\Datasets\Data for Tableau for NO2 CO2 PM\5 high Data


In [19]:
df = pd.read_csv("data_SO2_Jharkhand_2011-2014.csv");
df

State  SO2  Year
0  Jharkhand   23  2011
1  Jharkhand   23  2012
2  Jharkhand   23  2013
3  Jharkhand   23  2014

In [4]:
df_so2 = pd.DataFrame()
df_so2["Year"] = df["Year"]
df_so2["State"] = df["State"]
df_so2["SO2"] = df["SO2"]
df_so2

Year      State   SO2
0  2011  Jharkhand  23.0
1  2012  Jharkhand  23.0
2  2013  Jharkhand  23.0
3  2014  Jharkhand   NaN

In [6]:
le = LabelEncoder()
state = le.fit_transform(df_so2["State"])
df_so2["state_encoded"] = state
df_so2

Year      State   SO2  state_encoded
0  2011  Jharkhand  23.0              0
1  2012  Jharkhand  23.0              0
2  2013  Jharkhand  23.0              0
3  2014  Jharkhand   NaN              0

In [7]:
df_so2.drop('State',axis=1,inplace=True)

In [8]:
df_2014 = df_so2.loc[df_so2["Year"]==2014]
test_2014 = df_2014
test_2014

Year  SO2  state_encoded
3  2014  NaN              0

In [10]:
train_2011_13 = df_so2.head(3)
train_2011_13

Year   SO2  state_encoded
0  2011  23.0              0
1  2012  23.0              0
2  2013  23.0              0

In [11]:
#x_train,x_test,y_train,y_test = train_test_split(train_2011_14,test_2015_2016,test_size=0.3,random_state=0)
x_train = train_2011_13.drop("SO2",axis=1)
y_train = train_2011_13["SO2"].copy()
x_test = test_2014.drop("SO2",axis=1)
y_test = test_2014["SO2"].copy()

In [12]:
lr = LinearRegression()
lr_fir = lr.fit(x_train,y_train)
pred = lr.predict(x_test)
pred

array([23.])

In [13]:
test_2014["SO2"] = pred
test_2014

<ipython-input-13-f4e96cafb548>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_2014["SO2"] = pred


Year   SO2  state_encoded
3  2014  23.0              0

In [21]:
df = pd.read_csv("data_SO2_uttarakhand_2011-2014.csv");
df
df_so2_Uttarakhand = pd.DataFrame()
df_so2_Uttarakhand["Year"] = df["Year"]
df_so2_Uttarakhand["State"] = df["State"]
df_so2_Uttarakhand["SO2"] = df["SO2"]
df_so2_Uttarakhand

Year        State   SO2
0  2011  Uttarakhand  21.0
1  2012  Uttarakhand   9.0
2  2013  Uttarakhand  21.0
3  2014  Uttarakhand   NaN

In [22]:
le = LabelEncoder()
state = le.fit_transform(df_so2_Uttarakhand["State"])
df_so2_Uttarakhand["state_encoded"] = state
df_so2_Uttarakhand

Year        State   SO2  state_encoded
0  2011  Uttarakhand  21.0              0
1  2012  Uttarakhand   9.0              0
2  2013  Uttarakhand  21.0              0
3  2014  Uttarakhand   NaN              0

In [23]:
df_so2_Uttarakhand.drop('State',axis=1,inplace=True)

In [26]:
df_2014 = df_so2_Uttarakhand.loc[df_so2_Uttarakhand["Year"]==2014]
test_2014 = df_2014
test_2014

Year  SO2  state_encoded
3  2014  NaN              0

In [27]:
train_2011_13 = df_so2_Uttarakhand.head(3)
train_2011_13

Year   SO2  state_encoded
0  2011  21.0              0
1  2012   9.0              0
2  2013  21.0              0

In [28]:
#x_train,x_test,y_train,y_test = train_test_split(train_2011_14,test_2015_2016,test_size=0.3,random_state=0)
x_train = train_2011_13.drop("SO2",axis=1)
y_train = train_2011_13["SO2"].copy()
x_test = test_2014.drop("SO2",axis=1)
y_test = test_2014["SO2"].copy()

In [29]:
lr = LinearRegression()
lr_fir = lr.fit(x_train,y_train)
pred = lr.predict(x_test)
pred

array([17.])

In [30]:
test_2014.to_csv("E:\M.Sc(DS & SA)\Sem-2\Data Driven Governance\Final Project Data\Datasets\Data for Tableau for NO2 CO2 PM\State wise Predict Data\pred_2014_Uttarakhand_so2.csv", index = False)

In [32]:
df = pd.read_csv("data_SO2_maharastra_2011-2014.csv");
df
df_so2_maharastra = pd.DataFrame()
df_so2_maharastra["Year"] = df["Year"]
df_so2_maharastra["State"] = df["State"]
df_so2_maharastra["SO2"] = df["SO2"]
df_so2_maharastra

Year        State   SO2
0  2011  Maharashtra  18.0
1  2012  Maharashtra  17.0
2  2013  Maharashtra  18.0
3  2014  Maharashtra   NaN

In [33]:
le = LabelEncoder()
state = le.fit_transform(df_so2_maharastra["State"])
df_so2_maharastra["state_encoded"] = state
df_so2_maharastra

Year        State   SO2  state_encoded
0  2011  Maharashtra  18.0              0
1  2012  Maharashtra  17.0              0
2  2013  Maharashtra  18.0              0
3  2014  Maharashtra   NaN              0

In [34]:
df_so2_maharastra.drop('State',axis=1,inplace=True)

In [35]:
df_2014 = df_so2_maharastra.loc[df_so2_maharastra["Year"]==2014]
test_2014 = df_2014
test_2014

Year  SO2  state_encoded
3  2014  NaN              0

In [36]:
train_2011_13 = df_so2_maharastra.head(3)
train_2011_13

Year   SO2  state_encoded
0  2011  18.0              0
1  2012  17.0              0
2  2013  18.0              0

In [37]:
#x_train,x_test,y_train,y_test = train_test_split(train_2011_14,test_2015_2016,test_size=0.3,random_state=0)
x_train = train_2011_13.drop("SO2",axis=1)
y_train = train_2011_13["SO2"].copy()
x_test = test_2014.drop("SO2",axis=1)
y_test = test_2014["SO2"].copy()

In [38]:
lr = LinearRegression()
lr_fir = lr.fit(x_train,y_train)
pred = lr.predict(x_test)
pred

array([17.66666667])

In [39]:
test_2014["SO2"] = pred
test_2014

<ipython-input-39-f4e96cafb548>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_2014["SO2"] = pred


Year        SO2  state_encoded
3  2014  17.666667              0

In [40]:
test_2014.to_csv("E:\M.Sc(DS & SA)\Sem-2\Data Driven Governance\Final Project Data\Datasets\Data for Tableau for NO2 CO2 PM\State wise Predict Data\pred_2014_maharastra_so2.csv", index = False)

In [42]:
df = pd.read_csv("data_SO2_meghalaya_2011-2014.csv");
df
df_so2_meghalaya = pd.DataFrame()
df_so2_meghalaya["Year"] = df["Year"]
df_so2_meghalaya["State"] = df["State"]
df_so2_meghalaya["SO2"] = df["SO2"]
df_so2_meghalaya

Year      State   SO2
0  2011  Meghalaya  17.0
1  2012  Meghalaya   2.0
2  2013  Meghalaya  17.0
3  2014  Meghalaya   NaN

In [43]:
le = LabelEncoder()
state = le.fit_transform(df_so2_meghalaya["State"])
df_so2_meghalaya["state_encoded"] = state
df_so2_meghalaya

Year      State   SO2  state_encoded
0  2011  Meghalaya  17.0              0
1  2012  Meghalaya   2.0              0
2  2013  Meghalaya  17.0              0
3  2014  Meghalaya   NaN              0

In [44]:
df_so2_meghalaya.drop('State',axis=1,inplace=True)

In [45]:
df_2014 = df_so2_meghalaya.loc[df_so2_meghalaya["Year"]==2014]
test_2014 = df_2014
test_2014

Year  SO2  state_encoded
3  2014  NaN              0

In [46]:
train_2011_13 = df_so2_meghalaya.head(3)
train_2011_13

Year   SO2  state_encoded
0  2011  17.0              0
1  2012   2.0              0
2  2013  17.0              0

In [47]:
#x_train,x_test,y_train,y_test = train_test_split(train_2011_14,test_2015_2016,test_size=0.3,random_state=0)
x_train = train_2011_13.drop("SO2",axis=1)
y_train = train_2011_13["SO2"].copy()
x_test = test_2014.drop("SO2",axis=1)
y_test = test_2014["SO2"].copy()

In [48]:
lr = LinearRegression()
lr_fir = lr.fit(x_train,y_train)
pred = lr.predict(x_test)
pred



array([12.])

In [49]:
test_2014["SO2"] = pred
test_2014

<ipython-input-49-f4e96cafb548>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_2014["SO2"] = pred


Year   SO2  state_encoded
3  2014  12.0              0

In [50]:
test_2014.to_csv("E:\M.Sc(DS & SA)\Sem-2\Data Driven Governance\Final Project Data\Datasets\Data for Tableau for NO2 CO2 PM\State wise Predict Data\pred_2014_meghalaya_so2.csv", index = False)